### ISSUE TITLE
TypeError: null is not a object (evaluting 'RNGiphyUI.configure')

### ISSUE THREAD

**Issue by harshal2030** [jesster2k10/react-native-giphy-ui#1]
![Screenshot from 2020-04-13 20-24-29](https://user-images.githubusercontent.com/43959510/79130719-130efc80-7dc5-11ea-9e72-4b03aaadf223.png)
`import {GiphyUi} from 'react-native-giphy-ui' ;
GiphyUi.configure('MY_API_KEY');
showGIF = () => {
        GiphyUi.present(
            {
                theme: 'dark',
                layout: 'carousel',
                showConfirmationScreen: false,
                mediaType: ['gifs'],
            },
            selectedMedia => {
                console.log(selectedMedia);
            },
        );
    };
`

**Comment by harshal2030** [comment]
Is there any idea of fixing this bug.

**Comment by jesster2k10** [comment]
Hey, as of right now android support is experimental, so it’s likely not to work as well as the iOS counterparts. However, it should still work. I’ll investigate this issue later today, the likely cause is a miss hap in declaring the name of the native module class. So it should be a quick fix.

**Comment by harshal2030** [comment]
Thanks for your quick response, waiting for the fix

**Comment by jesster2k10** [comment]
This issue has now been fixed in the latest `0.20.0` release and android support has been completed. You can now update the package from yarn/npm like so:

```bash
yarn add react-native-giphy-ui@latest
```

**Comment by harshal2030** [comment]
Thank you for your support
**This is really a great repo. Wish more people would know about this**
